

google/gemma-2b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

google/gemma-7b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1
