

microsoft/phi-3-mini-4k-instruct:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  num_train_epochs: 5
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.05

google/gemma-7b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1
